#compdef unicli

# zsh completion for unicli
# Generated by: unicli completion zsh
# To regenerate: unicli completion zsh > completions/unicli.zsh
#
# Manual install:
#   Place this file in a directory on your $fpath, e.g.:
#   cp completions/unicli.zsh ~/.zsh/completions/_unicli
#   OR add to ~/.zshrc:
#   source <(unicli completion zsh)

# zsh completions require compinit to be loaded.
# Make sure your ~/.zshrc contains:
#   autoload -Uz compinit && compinit

__unicli_debug()
{
    local file="${BASH_COMP_DEBUG_FILE:-}"
    if [[ -n ${file} ]]; then
        echo "$*" >> "${file}"
    fi
}

_unicli()
{
    local shellCompDirectiveError=1
    local shellCompDirectiveNoSpace=4
    local shellCompDirectiveNoFileComp=8
    local shellCompDirectiveFilterFileExt=16
    local shellCompDirectiveFilterDirs=32
    local shellCompDirectiveKeepOrder=64

    local lastParam=${words[-1]}
    local flagPrefix=""

    __unicli_debug "========= starting completion logic =========="
    __unicli_debug "words: ${words[@]}"
    __unicli_debug "last word: ${lastParam}"

    # Request completions from the binary
    local requestComp="${words[1]} __complete ${words[2,-1]}"
    if [[ ${lastParam} != "=" ]]; then
        requestComp="${requestComp} ''"
    fi

    __unicli_debug "requestComp: ${requestComp}"

    local out directive
    out=$(eval "${requestComp}" 2>/dev/null)
    directive="${out##*$'\n'}"
    out="${out%$'\n'*}"

    __unicli_debug "directive: ${directive}"
    __unicli_debug "completions: ${out}"

    if [[ -z "${directive}" ]]; then
        directive=0
    fi

    local activeHelpMarker="_activeHelp_ "
    local endIndex=${#activeHelpMarker}
    local hasActiveHelp=0

    local completions=()
    local descriptions=()
    local comp

    while IFS='\n' read -r comp; do
        if [[ ${comp:0:${endIndex}} == ${activeHelpMarker} ]]; then
            __unicli_debug "activeHelp: ${comp}"
            hasActiveHelp=1
            comp="${comp:${endIndex}}"
        fi

        if [[ -n ${comp} ]]; then
            # Split on tab — left side is completion, right side is description
            local compWithDesc
            IFS=$'\t' read -r comp compWithDesc <<< "${comp}"
            completions+=("${comp}")
            descriptions+=("${compWithDesc}")
        fi
    done < <(printf "%s\n" "${out}")

    __unicli_debug "completions: ${completions[@]}"

    if [[ $((directive & shellCompDirectiveError)) -ne 0 ]]; then
        __unicli_debug "Error from completion binary"
        return
    fi

    local nospace=0
    if [[ $((directive & shellCompDirectiveNoSpace)) -ne 0 ]]; then
        __unicli_debug "No space directive set"
        nospace=1
    fi

    local nofilecomp=0
    if [[ $((directive & shellCompDirectiveNoFileComp)) -ne 0 ]]; then
        __unicli_debug "No file completion directive set"
        nofilecomp=1
    fi

    if [[ ${#completions[@]} -ne 0 ]]; then
        local compsWithDescriptions=()
        local i
        for (( i=0; i < ${#completions[@]}; i++ )); do
            if [[ -n "${descriptions[$i]}" ]]; then
                compsWithDescriptions+=("${completions[$i]}:${descriptions[$i]}")
            else
                compsWithDescriptions+=("${completions[$i]}")
            fi
        done

        if [[ $nospace -ne 0 ]]; then
            compadd -S '' -a compsWithDescriptions
        else
            compadd -a compsWithDescriptions
        fi
    elif [[ $nofilecomp -ne 0 ]]; then
        __unicli_debug "No file completion"
        compadd ""
    fi
}

# Subcommand completions
_unicli_commands()
{
    local commands=(
        "setup:Install required dependencies and configure unicli"
        "download:Download from any URL"
        "completion:Manage shell completion scripts"
        "alias:Manage the unicli invocation alias"
    )
    _describe "commands" commands
}

_unicli_download_flags()
{
    local flags=(
        "--output[Output directory]:directory:_files -/"
        "--format[Force output format]:format:(mp4 mp3 webm mkv m4a flac wav ogg)"
        "--quality[Video quality]:quality:(best 1080p 720p 480p 360p 240p)"
        "--audio-only[Extract audio only]"
        "--no-metadata[Skip embedding metadata]"
        "--dry-run[Show what would happen without executing]"
        "--verbose[Show detailed output]"
        "--quiet[Suppress output except errors]"
        "--yes[Skip confirmation prompts]"
    )
    _arguments -s "${flags[@]}"
}

_unicli_completion_subcommands()
{
    local subcommands=(
        "install:Install completion script into your shell config"
        "bash:Print bash completion script to stdout"
        "zsh:Print zsh completion script to stdout"
        "fish:Print fish completion script to stdout"
    )
    _describe "subcommands" subcommands
}

_unicli_alias_subcommands()
{
    local subcommands=(
        "set:Set a custom alias for unicli"
        "get:Show the current alias"
        "reset:Remove alias and return to unicli"
    )
    _describe "subcommands" subcommands
}

# Main dispatcher
_unicli_main()
{
    local state

    _arguments \
        '1: :_unicli_commands' \
        '*:: :->subcmd' \
        '--verbose[Show detailed output]' \
        '--quiet[Suppress output except errors]' \
        '--dry-run[Show what would happen without executing]' \
        '--yes[Skip confirmation prompts]' \
        '--version[Print version and exit]' \
        '--help[Show help]' \
        && return

    case $state in
        subcmd)
            case $words[1] in
                download)
                    _unicli_download_flags
                    ;;
                completion)
                    _unicli_completion_subcommands
                    ;;
                alias)
                    _unicli_alias_subcommands
                    ;;
            esac
            ;;
    esac
}

_unicli_main "$@"
