# bash completion for unicli
# Generated by: unicli completion bash
# To regenerate: unicli completion bash > completions/unicli.bash
#
# Manual install:
#   source completions/unicli.bash
#   OR add to ~/.bashrc:
#   source <(unicli completion bash)

# bash completion V2 — requires bash 4.1+
# On macOS, the default bash is 3.x — install bash via Homebrew:
#   brew install bash

__unicli_debug()
{
    if [[ -n ${BASH_COMP_DEBUG_FILE:-} ]]; then
        echo "$*" >> "${BASH_COMP_DEBUG_FILE}"
    fi
}

__unicli_perform_completion()
{
    __unicli_debug "${FUNCNAME[0]}"

    # Extract all args except the last one
    local lastParam lastChar flagPrefix requestComp out directive comp lastComp noSpace

    lastParam=${COMP_WORDS[$((${#COMP_WORDS[@]} - 1))]}
    lastChar=${lastParam:$((${#lastParam} - 1)):1}

    __unicli_debug "lastParam: ${lastParam}, lastChar: ${lastChar}"

    # Build the request completions command
    requestComp="${COMP_WORDS[0]} __complete ${COMP_WORDS[*]:1}"
    if [[ ${lastChar} != = ]]; then
        requestComp="${requestComp} ''"
    fi

    __unicli_debug "requestComp: ${requestComp}"

    # Run the completion command
    out=$(eval "${requestComp}" 2>/dev/null)
    directive=${out##*$'\n'}
    out=${out%$'\n'*}

    __unicli_debug "directive: ${directive}"
    __unicli_debug "completions: ${out}"

    if [[ ${directive} == "" ]]; then
        directive=0
    fi

    local activeHelpMarker="_activeHelp_ "
    local endIndex=${#activeHelpMarker}
    local startIndex=$((${#activeHelpMarker} - 1))
    local hasActiveHelp=0

    while IFS='\n' read -r comp; do
        # Check for activeHelp
        if [[ ${comp:0:${endIndex}} == ${activeHelpMarker} ]]; then
            __unicli_debug "activeHelp: ${comp}"
            hasActiveHelp=1
            comp=${comp:${endIndex}}
        fi

        if [[ -n ${comp} ]]; then
            COMPREPLY+=("${comp}")
        fi
    done < <(printf "%s\n" "${out}")

    __unicli_debug "COMPREPLY: ${COMPREPLY[*]}"

    # Apply directives
    if [[ $((directive & 1)) -ne 0 ]]; then
        __unicli_debug "Disabling file completion"
        compopt +o default
    fi

    if [[ $((directive & 2)) -ne 0 ]]; then
        __unicli_debug "Requesting filename completion"
        if [[ ${#COMPREPLY[@]} -ne 0 ]]; then
            compopt -o filenames
        else
            COMPREPLY=()
            compopt -o default
        fi
    fi

    if [[ $((directive & 4)) -ne 0 ]]; then
        __unicli_debug "Requesting no space after completion"
        compopt -o nospace
    fi
}

__unicli_handle_reply()
{
    __unicli_debug "${FUNCNAME[0]}"
    local comp

    case $cur in
        -*)
            if [[ $(type -t compopt) = "builtin" ]]; then
                compopt -o nospace
            fi
            local allflags
            if [[ ${#COMP_WORDS[@]} == 1 ]]; then
                allflags=("${flagsWithCompletion[@]}" "${mustHaveArgs[@]}")
            else
                allflags=("${flags[@]}" "${flagsWithCompletion[@]}" "${mustHaveArgs[@]}")
            fi
            while IFS='' read -r comp; do
                COMPREPLY+=("$comp")
            done < <(compgen -W "${allflags[*]}" -- "$cur")
            if [[ $(type -t compopt) = "builtin" ]]; then
                [[ ${COMPREPLY[0]} == *= ]] || compopt +o nospace
            fi
            return 0
            ;;
    esac
}

__unicli_root_command()
{
    local commands=(
        "setup"
        "download"
        "completion"
        "alias"
        "--help"
        "--verbose"
        "--quiet"
        "--dry-run"
        "--yes"
        "--version"
    )
    COMPREPLY=($(compgen -W "${commands[*]}" -- "$cur"))
}

_unicli()
{
    local cur prev words cword
    declare -A flagsWithCompletion
    declare -A flagsNoSpace

    if declare -F _init_completion >/dev/null 2>&1; then
        _init_completion -s || return
    else
        COMPREPLY=()
        _get_comp_words_by_ref -n "=:" cur prev words cword
    fi

    __unicli_perform_completion
}

complete -F _unicli -o nosort unicli
