# fish completion for unicli
# Generated by: unicli completion fish
# To regenerate: unicli completion fish > completions/unicli.fish
#
# Manual install:
#   cp completions/unicli.fish ~/.config/fish/completions/unicli.fish
#   OR add to ~/.config/fish/config.fish:
#   unicli completion fish | source

# Disable file completions for all unicli commands by default
complete -c unicli -f

# ── Global flags ────────────────────────────────────────────────────────────

complete -c unicli -n "__fish_use_subcommand" -l verbose   -s v -d "Show detailed output"
complete -c unicli -n "__fish_use_subcommand" -l quiet     -s q -d "Suppress output except errors"
complete -c unicli -n "__fish_use_subcommand" -l dry-run        -d "Show what would happen without executing"
complete -c unicli -n "__fish_use_subcommand" -l yes       -s y -d "Skip confirmation prompts"
complete -c unicli -n "__fish_use_subcommand" -l version        -d "Print version and exit"
complete -c unicli -n "__fish_use_subcommand" -l help      -s h -d "Show help"

# ── Top-level subcommands ───────────────────────────────────────────────────

complete -c unicli -n "__fish_use_subcommand" -a setup      -d "Install required dependencies and configure unicli"
complete -c unicli -n "__fish_use_subcommand" -a download   -d "Download from any URL"
complete -c unicli -n "__fish_use_subcommand" -a completion -d "Manage shell completion scripts"
complete -c unicli -n "__fish_use_subcommand" -a alias      -d "Manage the unicli invocation alias"

# ── setup ───────────────────────────────────────────────────────────────────

complete -c unicli -n "__fish_seen_subcommand_from setup" -l update  -d "Re-download latest versions of all engines"
complete -c unicli -n "__fish_seen_subcommand_from setup" -l verbose -d "Show detailed output"
complete -c unicli -n "__fish_seen_subcommand_from setup" -l quiet   -d "Suppress output except errors"
complete -c unicli -n "__fish_seen_subcommand_from setup" -l yes     -d "Skip confirmation prompts"
complete -c unicli -n "__fish_seen_subcommand_from setup" -l dry-run -d "Show what would happen without executing"

# ── download ─────────────────────────────────────────────────────────────────

complete -c unicli -n "__fish_seen_subcommand_from download" -l output    -s o -d "Output directory" -r -a "(__fish_complete_directories)"
complete -c unicli -n "__fish_seen_subcommand_from download" -l format    -s f -d "Force output format" -r -a "mp4 mp3 webm mkv m4a flac wav ogg"
complete -c unicli -n "__fish_seen_subcommand_from download" -l quality        -d "Video quality"      -r -a "best 1080p 720p 480p 360p 240p"
complete -c unicli -n "__fish_seen_subcommand_from download" -l audio-only     -d "Extract audio only"
complete -c unicli -n "__fish_seen_subcommand_from download" -l no-metadata    -d "Skip embedding metadata"
complete -c unicli -n "__fish_seen_subcommand_from download" -l dry-run        -d "Show what would happen without executing"
complete -c unicli -n "__fish_seen_subcommand_from download" -l verbose        -d "Show detailed output"
complete -c unicli -n "__fish_seen_subcommand_from download" -l quiet          -d "Suppress output except errors"
complete -c unicli -n "__fish_seen_subcommand_from download" -l yes            -d "Skip confirmation prompts"

# ── completion ───────────────────────────────────────────────────────────────

complete -c unicli -n "__fish_seen_subcommand_from completion; and not __fish_seen_subcommand_from install bash zsh fish" -a install -d "Install completion script into your shell config"
complete -c unicli -n "__fish_seen_subcommand_from completion; and not __fish_seen_subcommand_from install bash zsh fish" -a bash    -d "Print bash completion script to stdout"
complete -c unicli -n "__fish_seen_subcommand_from completion; and not __fish_seen_subcommand_from install bash zsh fish" -a zsh     -d "Print zsh completion script to stdout"
complete -c unicli -n "__fish_seen_subcommand_from completion; and not __fish_seen_subcommand_from install bash zsh fish" -a fish    -d "Print fish completion script to stdout"

complete -c unicli -n "__fish_seen_subcommand_from completion; and __fish_seen_subcommand_from install" -l shell -d "Shell to install for" -r -a "bash zsh fish"

# ── alias ────────────────────────────────────────────────────────────────────

complete -c unicli -n "__fish_seen_subcommand_from alias; and not __fish_seen_subcommand_from set get reset" -a set   -d "Set a custom alias for unicli"
complete -c unicli -n "__fish_seen_subcommand_from alias; and not __fish_seen_subcommand_from set get reset" -a get   -d "Show the current alias"
complete -c unicli -n "__fish_seen_subcommand_from alias; and not __fish_seen_subcommand_from set get reset" -a reset -d "Remove alias and return to unicli"
